### ISSUE TITLE
Not an editor command: IndentLineDisable

### ISSUE THREAD

**Issue by ghost** [metakirby5/dotfiles#3]
https://github.com/metakirby5/.dots/blob/5765e872b6dccc52c2aadfc4f5195da8cff0ed19/base/.vimrc#L65

Where is this command from?

**Comment by metakirby5** [comment]
It comes from this plugin:

https://github.com/metakirby5/.dots/blob/5765e872b6dccc52c2aadfc4f5195da8cff0ed19/base/.vimrc#L143

Thanks for checking out my dotfiles :)
